import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
//
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({ children }) {
//   return (
//     // 1. 在 html 标签添加 suppressHydrationWarning
//     <html lang="en" suppressHydrationWarning>
//       {/* 2. 在 body 标签添加 suppressHydrationWarning */}
//       <body
//         className={`antialiased`} // 这里保留你原本的 className
//         suppressHydrationWarning
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


export const metadata = {
    title: "Map App",
    description: "Historical Map Search",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning>
        {/* 2. 确保在 body 标签上也添加 suppressHydrationWarning */}
        <body
            // 这里的 className 保持您原本的字体设置
            className={`antialiased`}
            suppressHydrationWarning={true} // 🔥 强制屏蔽水合警告
        >
        {children}
        </body>
        </html>
    );
}